name: environment ltg

channels:
  - conda-forge
#  - bioconda
  - anaconda
  - gurobi
  - default

dependencies:
# Not suitable for windows  - coincbc=2.10.5              # Cbc (Coin-or branch and cut) mixed integer programming solver written in C++.
  - geopy=2.2.0                 # Python Geocoding Toolbox
  - geopandas=0.9.0             # Geographic pandas extensions   
  - glpk=5.0                    # GNU Linear Programming Kit. Solver.
  - gurobi=9.1.2                # Gurobi Optimizer
  - jupyterlab=3.1.4            # Jupyter environment for interactive and reproducible computing.
  - matplotlib=3.4.2            # Publication quality figures.
  - pandas=1.3.1                # High-performance, easy-to-use data structures and data analysis tools.
  - pypsa=0.18.0                # Python for Power System Analysis. Framework.
  - python=3.8.10               # Python Programming Language Version 3.8
  - spyder=5.0.5                # IDE for programming in python 
#  - tabulate=0.8.9              # Pretty-print tabular data in Python, a library and a command-line utility.
